ministryofjustice/operations-engineering-reports

lib/collaborators.rb, views/github_collaborators.erb
Only collaborators with issues (i.e. problems which need to be fixed)
will appear in the JSON data posted to this report. This change displays
those issues along with a link to the repo where the user can fix them.
=> Display issues with collaborators

views/github_collaborators.erb
This change shows the total number of collaborations which need
to be fixed (i.e. they need additional details provided, or haven't been
defined in terraform code yet).
This should make it easier to judge our progress in getting teams to
update the information in this repo.
=> Add a count to collaborators report

report_app/main/views.py
This PR is a value add. The previous route has not been adjusted.
I've tested this locally. This is the response from:
http://127.0.0.1:4567/api/v1/compliant_public_repositories/endpoint/operations-engineering
```
{
"color": "d4351c",
"label": "MoJ Compliant",
"message": "FAIL",
"schemaVersion": 1
}
```
Please let me know if you'd like the URL to be something different. Thank you.
=> Add a new API route for a deeper dynamic badge

report_app/main/views.py
Fix the colour issue on the FAIL response; the button colour stays blue because the user has specified it in the URL.
> When a user specifies `color=...` in the URL, shield.io honors this.
> When `isError=true`, shield.io will ignore the user-specified `color` in the URL.
Furthermore; the default MoJ blue has been applied to the PASS response.
=> Prevent user override on error

report_app/main/views.py
This PR adds our logo to the API response for users who use the `endpoint` badge.
This means that the logo doesn't need to be specified in the badge code. It shall appear.
Dev note: there is probably a better way of referencing the base64 code for use in the method.
Please advise 👍🏽 
Thanks
=> Add our crest to the response

report_app/main/views.py
This removes unsupported base64 code from the badge request API response :(
It also adds the `for-the-badge` style as a backup to the API JSON response.
=> Remove base64 add badge style

report_app/main/views.py
Adds the `labelColor` property to the badge API PASS response. 
This will make our badge code less reliant on configuration.
=> Add labelColor to badge API PASS response

.github/workflows/deploy-to-dev.yml
The Helm test command can be very useful, but it doesn't run in Cloud Platform in its current inplementation. You cannot run root images in CP unless you're an admin, and we are not. Until this is replaced with something better I think it's best to remove the test.
=> :stethoscope: Remove broken Helm test until it can be replaced

report_app/main/report_database.py, report_app/main/views.py, report_app/templates/all-public-repositories.html, report_app/templates/compliant-public-repositories.html, report_app/templates/non-compliant-public-repositories.html, report_app/templates/public-github-repositories.html, tests/test_report_database.py, tests/test_views.py
Overview
---
This PR connects to https://github.com/ministryofjustice/operations-engineering/issues/2272 and https://github.com/ministryofjustice/operations-engineering/issues/2243 and relates to the addition of three new Flask views and one change (with tests).
View:
1. `report_app/templates/all-public-repositories.html` displays a boxed view of all collected public repositories. It should identify at a glance the mass of repositories and allow users to visually see their repository report.
---
2. `report_app/templates/compliant-public-repositories.html` simply captures the name and places it into a table. There wasn't a lot to do here, other than linking it to other pages.
---
3. `report_app/templates/non-compliant-public-repositories.html` will display a table of all offending …
=> ✨ Add links to high level report overview

.github/workflows/pytest.yml, makefile, report_app/config/development.py, report_app/main/views.py, tests/test_views.py
The flask environment requires several environment variables set in a test environment. This PR adds the `FLASK_CONFIGURATION=development` envvar to the `make test` command, which will set a number of variables at runtime.
=> ✅ Add flask envvars to testing environment

report_app/templates/base.html
The global base logout button has a place on only a few of our pages. It makes navigation confusing and needs to look better.
This PR removes the logout button from the base template and formats the HTML code.
=> 🔥 Remove the logout button from all pages

helm/operations-engineering-reports/templates/deployment.yaml
Cloud Platform are moving away from long-lived credentials. This means we must use the service account module as defined in this document: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/accessing-aws-apis-and-resources-from-your-namespace.html#using-irsa-in-your-namespace
=> :closed_lock_with_key: Set service name to that defined in CP IRSA

report_app/main/report_database.py, tests/test_report_database.py
This is actually already done by Cloud Platform and all we need to do it create the connection.
=> 🔥  Remove need to assume role on db connection

helm/operations-engineering-reports/templates/ingress.yaml, makefile
This PR significantly refactors the makefile to improve maintainability, efficiency, and user-friendliness. Below are the key changes:
The `.ONESHELL` directive is added to ensure that all commands in a target run in a single shell. This simplifies the management of variables and conditions across multi-line commands.
Several configurable variables have been introduced to allow for greater flexibility when running make commands. These variables include:
- `RELEASE_NAME`
- `AUTH0_CLIENT_ID`
- `AUTH0_CLIENT_SECRET`
- `APP_SECRET_KEY`
- `ENCRYPTION_KEY`
- `API_KEY`
- `HOST_SUFFIX`
- `IMAGE`
- `REGISTRY`
These variables can be overridden by passing arguments to the `make` command.
A new `help` target has been added to display available commands, making it easier for users to understand the …
=> Add deploy-dev make file command

.github/workflows/deploy-to-dev.yml
Connects to https://github.com/ministryofjustice/operations-engineering/issues/3249.
This commit makes the required changes to remove long-lived Cloud Platform credentials and replaces them with an AWS Role specifically created to be assumed by the pipeline. 
Source: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/container-repositories/deprecating-long-lived-credentials.html#migrating-to-short-lived-credentials-for-github-actions
=> :construction_worker: Use ECR role rather than credentials + format

.github/workflows/deploy-to-dev.yml
When deploying the application, an error message appeared: invalid
reference format
Upon further investigation it transpires the new way of building and
pushing an image was missing the ECR prefix. This change corrects that
in the dev environment.
=> :bug: Fix incorrect image string interpolation in dev

.github/workflows/deploy-to-prod.yml
The image name is incorrectly interpolated due to local variables defining different values in different jobs. This change moves those local variables to a global scope and makes the same value availble to all jobs.
=> :green_heart: Fix prod container image name

.github/workflows/deploy-to-prod.yml
A 404 error appears when trying to create a release. Making this change will enable it to work according to this link: https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128
=> :green_heart: Fix permission when trying to create a release

Dockerfile, docker-test.yaml
This is due to a few trivy vulns triggering that debian are too slow to patch.
connect to https://github.com/ministryofjustice/operations-engineering/issues/3758
=> :wrench: Replace base build with Alpine image

Dockerfile
After running a local trivy container scan, this mitigates CVE2023-5363.
Results of previous trivy scan:
```bash
└─> docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
aquasec/trivy:latest image test-report --severity HIGH,CRITICAL
2023-11-20T10:51:19.187Z        INFO    Need to update DB
2023-11-20T10:51:19.187Z        INFO    DB Repository: ghcr.io/aquasecurity/trivy-db
2023-11-20T10:51:19.187Z        INFO    Downloading DB...
6.26 MiB / 40.91 MiB [--------->____________________________________________________] 15.31% ? p/s ?14.03 MiB / 40.91 MiB [-------------------->________________________________________] 34.30% ? p/s ?15.91 MiB / 40.91 MiB [----------------------->_____________________________________] 38.88% ? p/s ?22.47 MiB / 40.91 MiB …
```
=> :wrench: Bump base container to 3.18 and upgrade crypto pkgs

Dockerfile
- Oddly, this library is included in the base image - but I can't seem to find it when spinning up the image locally which causes Docker build issues locally
- Explicitly add `libffi-dev` to the image to resolve local build issue
=> ✨ Add `libffi-dev` to Docker build to resolve local build issues

README.md
This commit updates several references within the project's README:
- Replace outdated URLs to Operations Engineering Team and GitHub Repository Standards with their updated versions.
- Update Python prerequisite from a fixed 3.11 version to Python version 3.11 or later.
- Revise descriptions of what constitutes a repository report for clarity and accuracy.
- Modify link to GitHub Action that generates the report.
- Changed test organization for generating test reports.
These changes ensure that the README remains accurate and up-to-date with the latest information about the project and its requirements.
=> :pencil2: Update URLs, Python version and repository details in README

Dockerfile
This commit adds a new `HEALTHCHECK` instruction to our Dockerfile which uses curl to monitor the health of our app at regular intervals. The commit also introduces `curl` as an additional dependency, which gets installed during the docker build process.
We moved the declaration of `build-base` and `libffi-dev` each to their own line for better readability. Furthermore, we have separated out the installation of new packages from the existing chain of package updates and upgrades to keep things clean and separate.
=> :whale: Update Dockerfile with health check and additional dependencies

requirements.txt
Both were identified in the latest Trivy run that report the following
cves:
https://github.com/ministryofjustice/operations-engineering-reports/security/code-scanning/9
https://github.com/ministryofjustice/operations-engineering-reports/security/code-scanning/10
=> :arrow_up: Bump Authlib and requests packages following cve

Pipfile, Pipfile.lock
This pull request includes a small change to the `Pipfile`. The change adds a specific version requirement for the `setuptools` package.
https://github.com/ministryofjustice/operations-engineering-reports/security/code-scanning/11
* [`Pipfile`](diffhunk://#diff-230078d672f10d17463a8a6265cad825b790885898256a3365be90685caac58dR18): Added `setuptools` with version `==75.2.0` to the package dependencies.
=> :arrow_up: Bump setuptools to 75.2.0

README.md
This PR updates link to guidance that has recently moved to the Operations Engineering User Guide
=> Update Storing Code Link

helm/operations-engineering-reports/templates/ingress.yaml
- In relation to https://github.com/ministryofjustice/github-community/issues/27
- To migrate the legacy domain to the new service, to minimise disruption on existing users
- Added required annotations to start migrating the legacy domain to the new service
=> ✨ Add Required Annotations to Migrate Hostname
